# Generated by Django 4.0.3 on 2022-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='credits',
            field=models.CharField(default=4, max_length=255),
        ),
        migrations.AddField(
            model_name='subjects',
            name='semester',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
