# Generated by Django 4.0.3 on 2022-03-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_remove_subjects_credits_remove_subjects_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
    ]
